"""HTML report generator - modern "incident console" theme.

Renders a validated :class:`RCAReport` into a single, self-contained, styled
HTML document that mirrors the PDF section order and every Phase 4 quality
field. The visual language (a light canvas, soft elevated cards, one indigo
accent, generous whitespace) is shared with the Phase 6 web UI so the inline
view, the saved ``Agentic_RCA.html`` and a printed page all feel like one
product.

Public API
----------
``build_html(report)``
    A full, standalone HTML document with all styles inlined and an optional
    Mermaid 5-Why tree. This is what the pipeline saves beside the PDF/JSON and
    what the web UI embeds inline.
``render_report_body(report)``
    Just the semantic ``<article>`` body, for callers that supply their own
    document shell.

The Mermaid 5-Why tree (Day 36 secondary, first kill-list item) is fully
self-contained: it enhances the always-present, readable why-chain stepper and
degrades gracefully to a note if the library cannot load (e.g. offline).
"""

from __future__ import annotations

import json
from datetime import datetime
from html import escape
from typing import Any

from schemas import RCAReport

ACCENT = "#ea580c"

CONFIDENCE_COLORS = {
    "high": "#16a34a",
    "medium": "#d97706",
    "low": "#dc2626",
}

METHOD_LABELS = {
    "five_why": "Why-chain (5 Whys)",
    "fishbone": "Fishbone (Ishikawa)",
    "fault_tree": "Fault Tree (simplified)",
}

DISCLAIMER = (
    "This root cause analysis was generated by an AI system from a plain-English "
    "problem statement. It is a reasoning aid, not a verdict: validate the causal "
    "chain against logs, metrics, and timelines before acting on it."
)

# Shared design tokens + component styles. Kept as one string so the standalone
# file, the web UI and the print layout all draw from a single source of truth.
REPORT_CSS = """
:root{
  --accent:#ea580c; --accent-2:#0f766e; --accent-3:#4f46e5; --accent-soft:#fff7ed; --accent-ring:#fed7aa;
  --bg:#fff7ed; --surface:#ffffff; --ink:#1e2330; --ink-soft:#475067;
  --muted:#6b7280; --line:#e7e9f2; --line-strong:#d7dbea;
  --high:#16a34a; --medium:#d97706; --low:#dc2626;
  --radius:16px; --radius-sm:10px;
  --shadow:0 1px 2px rgba(16,24,40,.04), 0 8px 28px -12px rgba(31,38,95,.22);
  --shadow-soft:0 1px 2px rgba(16,24,40,.05);
  --mono:ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,monospace;
  --sans:"Inter",system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
}
*{box-sizing:border-box}
.rca-root{font-family:var(--sans);color:var(--ink);line-height:1.55;
  -webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}
.rca-report{max-width:920px;margin:0 auto}

/* Header band */
.rca-hero{position:relative;overflow:hidden;border-radius:var(--radius);
  background:linear-gradient(135deg,#ea580c 0%,#0f766e 52%,#4f46e5 100%);
  color:#fff;padding:30px 32px 28px;box-shadow:var(--shadow)}
.rca-hero::after{content:"";position:absolute;inset:0;
  background:linear-gradient(90deg,rgba(255,255,255,.18),rgba(255,255,255,0));
  pointer-events:none}
.rca-eyebrow{font-size:11px;letter-spacing:.14em;text-transform:uppercase;
  font-weight:700;opacity:.85;margin:0 0 6px}
.rca-title{font-size:27px;font-weight:800;letter-spacing:-.02em;margin:0;line-height:1.12}
.rca-hero-problem{margin:12px 0 0;max-width:62ch;font-size:14.5px;opacity:.95}
.rca-meta{position:relative;z-index:1;display:flex;flex-wrap:wrap;gap:8px;margin-top:18px}
.rca-tag{display:inline-flex;align-items:center;gap:6px;background:rgba(255,255,255,.16);
  border:1px solid rgba(255,255,255,.22);backdrop-filter:blur(2px);
  padding:4px 11px;border-radius:999px;font-size:12px;font-weight:600}
.rca-tag b{font-weight:700}
.rca-tag .mono{font-family:var(--mono);font-size:11.5px;font-weight:600}
.rca-chip{display:inline-flex;align-items:center;gap:7px;padding:5px 13px;border-radius:999px;
  font-size:12px;font-weight:800;letter-spacing:.04em;color:#fff;
  box-shadow:0 2px 10px rgba(0,0,0,.18)}
.rca-chip .dot{width:8px;height:8px;border-radius:50%;background:#fff;opacity:.95}

/* Body + sections */
.rca-body{margin-top:20px;display:flex;flex-direction:column;gap:16px}
.rca-card{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);
  padding:22px 24px;box-shadow:var(--shadow-soft)}
.rca-h2{display:flex;align-items:center;gap:10px;margin:0 0 14px;
  font-size:13px;font-weight:800;letter-spacing:.07em;text-transform:uppercase;color:var(--accent)}
.rca-h2::before{content:"";width:6px;height:18px;border-radius:3px;
  background:linear-gradient(180deg,var(--accent),var(--accent-2))}
.rca-h2 .count{margin-left:auto;font-size:11px;font-weight:700;letter-spacing:0;
  color:var(--muted);background:var(--accent-soft);border-radius:999px;padding:2px 9px;text-transform:none}
.rca-prose{margin:0;font-size:15px;color:var(--ink-soft)}
.rca-lead{font-size:16px;color:var(--ink);line-height:1.6}

/* Why-chain stepper */
.why{position:relative;margin:2px 0 0;padding:0;list-style:none}
.why-step{position:relative;padding:0 0 22px 52px}
.why-step:last-child{padding-bottom:2px}
.why-step::before{content:"";position:absolute;left:17px;top:30px;bottom:-2px;width:2px;
  background:linear-gradient(180deg,var(--accent-ring),var(--line))}
.why-step:last-child::before{display:none}
.why-node{position:absolute;left:0;top:0;width:36px;height:36px;border-radius:50%;
  display:grid;place-items:center;font-weight:800;font-size:14px;color:#fff;
  background:linear-gradient(135deg,var(--accent),var(--accent-2));
  box-shadow:0 4px 12px -3px rgba(79,70,229,.55);border:3px solid #fff}
.why-q{font-weight:700;font-size:14.5px;color:var(--ink);margin:5px 0 4px}
.why-a{font-size:14px;color:var(--ink-soft);margin:0}
.why-step.is-root .why-node{background:linear-gradient(135deg,#0f172a,#334155)}

/* Root-cause callout */
.rca-root-cause{border:1px solid var(--accent-ring);background:
  linear-gradient(180deg,var(--accent-soft),#fff);border-left:5px solid var(--accent);
  border-radius:var(--radius-sm);padding:16px 18px}
.rca-root-cause .lbl{font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;
  color:var(--accent);margin:0 0 4px}
.rca-root-cause p{margin:0;font-size:16px;font-weight:600;color:var(--ink)}

/* Lists */
.rca-list{margin:0;padding:0;list-style:none;display:flex;flex-direction:column;gap:9px}
.rca-list li{position:relative;padding:11px 14px 11px 40px;background:#fbfbfe;
  border:1px solid var(--line);border-radius:var(--radius-sm);font-size:14px;color:var(--ink-soft)}
.rca-list.check li::before{content:"\\2713";position:absolute;left:13px;top:11px;
  color:var(--high);font-weight:800}
.rca-list.dot li::before{content:"";position:absolute;left:15px;top:18px;width:7px;height:7px;
  border-radius:50%;background:var(--accent)}
.rca-list.num{counter-reset:rec}
.rca-list.num li{counter-increment:rec}
.rca-list.num li::before{content:counter(rec);position:absolute;left:11px;top:9px;
  width:20px;height:20px;border-radius:6px;background:var(--accent-soft);color:var(--accent);
  font-weight:800;font-size:12px;display:grid;place-items:center}
.rca-list.notes li{background:#fff;border-style:dashed;color:var(--muted);
  font-size:13px;padding-left:14px}
.rca-list.notes li::before{display:none}
.rca-list.notes li .mono{font-family:var(--mono);font-size:11.5px;color:var(--accent)}

/* Past RCA memory */
.memory-top{border:1px solid var(--accent-ring);background:var(--accent-soft);
  border-radius:var(--radius-sm);padding:14px 15px}
.memory-tags{display:flex;flex-wrap:wrap;gap:7px;margin-bottom:10px}
.memory-tags span{display:inline-flex;border:1px solid var(--accent-ring);background:#fff;
  border-radius:7px;padding:3px 8px;font-size:11px;font-weight:700;color:var(--muted)}
.memory-tags .id{font-family:var(--mono);background:var(--accent);border-color:var(--accent);
  color:#fff}
.memory-label{font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;
  color:var(--accent);margin:0 0 4px}
.memory-root{margin:0;color:var(--ink);font-size:14.5px;font-weight:700}
.memory-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:11px}
.memory-box{border:1px solid var(--line);border-radius:8px;background:#fff;padding:9px 10px}
.memory-box p{margin:0;font-size:12.8px;color:var(--ink-soft)}
.memory-box .lbl{font-size:10.5px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;
  color:var(--muted);margin-bottom:3px}
.memory-reason{margin:11px 0 0;color:var(--muted);font-size:12.5px}
.memory-rest{display:grid;gap:8px;margin-top:10px}
.memory-row{border:1px solid var(--line);border-radius:9px;background:#fbfbfe;padding:10px 12px}
.memory-row p{margin:0}
.memory-row .id{font-family:var(--mono);font-size:12px;font-weight:800;color:var(--accent)}
.memory-row .root{font-size:13.5px;font-weight:700;color:var(--ink);margin-top:3px}
.memory-row .reason{font-size:12px;color:var(--muted);margin-top:2px}

/* Fishbone */
.fish{display:grid;gap:10px}
.fish-cat{border:1px solid var(--line);border-radius:var(--radius-sm);overflow:hidden}
.fish-cat .hd{display:flex;align-items:center;gap:9px;padding:9px 13px;background:#f7f8fd;
  font-weight:700;font-size:13px;color:var(--ink)}
.fish-cat .hd .badge{margin-left:auto;font-size:10.5px;font-weight:800;letter-spacing:.05em;
  text-transform:uppercase;color:var(--accent);background:var(--accent-soft);padding:2px 8px;border-radius:999px}
.fish-cat.sel{border-color:var(--accent-ring);box-shadow:0 0 0 3px var(--accent-soft)}
.fish-cat .bd{padding:9px 13px;font-size:13.5px;color:var(--ink-soft)}
.fish-cat .bd span{display:inline-block;background:#fff;border:1px solid var(--line);
  border-radius:7px;padding:3px 9px;margin:2px 4px 2px 0;font-size:12.5px}
.fish-pick{margin:4px 0 0;font-size:13.5px;color:var(--ink);background:var(--accent-soft);
  border:1px solid var(--accent-ring);border-radius:var(--radius-sm);padding:10px 13px}

/* Fault tree */
.ftree{margin:0;font-family:var(--sans)}
.ftree .top{font-weight:700;font-size:14.5px;color:var(--ink);margin:0 0 10px;
  padding:10px 13px;background:#f7f8fd;border:1px solid var(--line);border-radius:var(--radius-sm)}
.ftree ul{list-style:none;margin:0 0 0 8px;padding:0 0 0 16px;border-left:2px dashed var(--line-strong)}
.ftree>ul{border-left:none;padding-left:0;margin-left:0}
.ftree li{margin:8px 0}
.gate{display:inline-flex;align-items:center;gap:7px;font-weight:700;font-size:13.5px;color:var(--ink)}
.gate .g{font-family:var(--mono);font-size:11px;font-weight:800;color:#fff;
  background:var(--accent);border-radius:6px;padding:2px 7px;letter-spacing:.03em}
.gate .g.and{background:#0f172a}
.ftree .leaf{font-size:13.5px;color:var(--ink-soft)}
.ftree .basics{margin-top:12px}
.ftree .basics .lbl{font-size:11px;font-weight:800;letter-spacing:.06em;text-transform:uppercase;
  color:var(--muted);margin:0 0 6px}

/* Mermaid tree */
.tree-card .hint{font-size:12.5px;color:var(--muted);margin:-6px 0 12px}
.mermaid-wrap{border:1px solid var(--line);border-radius:var(--radius-sm);background:
  repeating-linear-gradient(0deg,#fcfcff,#fcfcff 23px,#f4f5fb 24px);
  padding:18px;overflow:auto;text-align:center;min-height:80px}
.mermaid{font-family:var(--sans)!important}
.mermaid svg .node:not(.root) .nodeLabel,.mermaid svg .node:not(.root) .label,
.mermaid svg .node:not(.root) foreignObject,.mermaid svg .node:not(.root) foreignObject *,
.mermaid svg .edgeLabel,.mermaid svg .edgeLabel *{color:#111827!important;fill:#111827!important}
.mermaid svg .node.root .nodeLabel,.mermaid svg .node.root .label,
.mermaid svg .node.root foreignObject,.mermaid svg .node.root foreignObject *{color:#ffffff!important;fill:#ffffff!important}
.mermaid svg .edgeLabel rect,.mermaid svg .labelBkg{background:#ffffff!important;fill:#ffffff!important;fill-opacity:.96!important}
.tree-fallback{display:none;font-size:13px;color:var(--muted);padding:10px 4px}
.tree-card.failed .mermaid{display:none}
.tree-card.failed .tree-fallback{display:block}

/* Disclaimer */
.rca-disclaimer{display:flex;gap:11px;align-items:flex-start;font-size:12.5px;color:var(--muted);
  background:#fbfbfe;border:1px dashed var(--line-strong);border-radius:var(--radius-sm);padding:13px 15px}
.rca-disclaimer .i{flex:0 0 auto;width:18px;height:18px;border-radius:50%;background:var(--accent-soft);
  color:var(--accent);font-weight:800;font-size:12px;display:grid;place-items:center;margin-top:1px}
.rca-empty{color:var(--muted);font-size:14px;font-style:italic}

@media (max-width:680px){
  .rca-hero{padding:24px 20px}.rca-title{font-size:23px}.rca-card{padding:18px 16px}
}
@media print{
  body{background:#fff!important}
  .rca-hero{box-shadow:none;-webkit-print-color-adjust:exact;print-color-adjust:exact}
  .rca-card{box-shadow:none;break-inside:avoid}
  .tree-card{break-inside:avoid}
}
"""

MERMAID_CDN = "https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"


# --------------------------------------------------------------------------- #
# Small helpers
# --------------------------------------------------------------------------- #
def _meta_tags(report: RCAReport) -> str:
    method_label = METHOD_LABELS.get(report.method or "", report.method or "")
    bits: list[str] = [
        f"<span class='rca-tag'>generated <b>{escape(datetime.now().strftime('%d %b %Y %H:%M'))}</b></span>",
    ]
    if method_label:
        bits.append(f"<span class='rca-tag'>method <b>{escape(method_label)}</b></span>")
    if report.source_model:
        bits.append(f"<span class='rca-tag'>model <span class='mono'>{escape(report.source_model)}</span></span>")
    if report.prompt_version:
        bits.append(f"<span class='rca-tag'>prompt <span class='mono'>{escape(report.prompt_version)}</span></span>")
    if report.latency_seconds is not None:
        bits.append(f"<span class='rca-tag'>latency <span class='mono'>{escape(str(report.latency_seconds))}s</span></span>")
    if report.known_issue_matches:
        bits.append(f"<span class='rca-tag'>memory <b>{len(report.known_issue_matches)} matches</b></span>")
    return "".join(bits)


def _confidence_chip(report: RCAReport) -> str:
    color = CONFIDENCE_COLORS.get(report.confidence, "#6b7280")
    return (
        f"<span class='rca-chip' style='background:{color}'>"
        f"<span class='dot'></span>MODEL VERDICT - {escape(report.confidence.upper())}</span>"
    )


def _list_card(title: str, items: list[str], variant: str) -> str:
    if not items:
        return ""
    rendered = "\n".join(f"<li>{escape(item)}</li>" for item in items)
    return (
        f"<section class='rca-card'><h2 class='rca-h2'>{escape(title)}"
        f"<span class='count'>{len(items)}</span></h2>"
        f"<ul class='rca-list {variant}'>{rendered}</ul></section>"
    )


def _notes_card(title: str, items: list[str]) -> str:
    if not items:
        return ""
    lis = []
    for item in items:
        text = escape(item)
        if item.startswith("[") and "]" in item:
            tag, rest = item.split("]", 1)
            text = f"<span class='mono'>{escape(tag + ']')}</span>{escape(rest)}"
        lis.append(f"<li>{text}</li>")
    return (
        f"<section class='rca-card'><h2 class='rca-h2'>{escape(title)}"
        f"<span class='count'>{len(items)}</span></h2>"
        f"<ul class='rca-list notes'>{''.join(lis)}</ul></section>"
    )


def _memory_section(report: RCAReport) -> str:
    matches = report.known_issue_matches
    if not matches:
        return ""

    total = len(matches)
    visible = matches[:3]
    top = visible[0]
    tags = [
        f"<span class='id'>{escape(top.incident_id)}</span>",
        f"<span>{round(top.similarity_score * 100)}% match</span>",
    ]
    if top.service_name:
        tags.append(f"<span>{escape(top.service_name)}</span>")
    if top.date:
        tags.append(f"<span>{escape(top.date)}</span>")

    boxes = []
    if top.immediate_fix:
        boxes.append(
            "<div class='memory-box'><p class='lbl'>Immediate fix</p>"
            f"<p>{escape(top.immediate_fix)}</p></div>"
        )
    if top.evidence_checked:
        boxes.append(
            "<div class='memory-box'><p class='lbl'>Evidence checked</p>"
            f"<p>{escape(top.evidence_checked)}</p></div>"
        )
    grid = f"<div class='memory-grid'>{''.join(boxes)}</div>" if boxes else ""
    rest = "".join(
        "<div class='memory-row'>"
        f"<p class='id'>{escape(match.incident_id)} - {round(match.similarity_score * 100)}% match</p>"
        f"<p class='root'>{escape(match.root_cause)}</p>"
        f"<p class='reason'>{escape(match.match_reason)}</p>"
        "</div>"
        for match in visible[1:]
    )
    rest_html = f"<div class='memory-rest'>{rest}</div>" if rest else ""
    summary = (
        f"<p class='memory-reason'>Found {total} matching past RCA record"
        f"{'s' if total != 1 else ''}. Showing top {len(visible)} here; "
        "download the Excel workbook for the full list.</p>"
    )

    return (
        "<section class='rca-card'><h2 class='rca-h2'>Past RCA Memory"
        f"<span class='count'>top {len(visible)} of {total}</span></h2>"
        "<div class='memory-top'>"
        f"<div class='memory-tags'>{''.join(tags)}</div>"
        "<p class='memory-label'>Known root cause</p>"
        f"<p class='memory-root'>{escape(top.root_cause)}</p>"
        f"{grid}"
        f"<p class='memory-reason'>{escape(top.match_reason)}</p>"
        "</div>"
        f"{rest_html}{summary}</section>"
    )


def _why_chain_section(report: RCAReport) -> str:
    steps = []
    last = len(report.why_chain) - 1
    for i, entry in enumerate(report.why_chain):
        root_cls = " is-root" if i == last else ""
        steps.append(
            f"<li class='why-step{root_cls}'>"
            f"<span class='why-node'>{entry.index}</span>"
            f"<p class='why-q'>{escape(entry.question)}</p>"
            f"<p class='why-a'>{escape(entry.answer)}</p></li>"
        )
    return (
        f"<section class='rca-card'><h2 class='rca-h2'>Why Chain"
        f"<span class='count'>{len(report.why_chain)} steps</span></h2>"
        f"<ol class='why'>{''.join(steps)}</ol></section>"
    )


def _fishbone_section(detail: dict[str, Any]) -> str:
    categories = detail.get("categories", {})
    if not isinstance(categories, dict) or not categories:
        return ""
    selected_category = detail.get("selected_category")
    selected_cause = detail.get("selected_cause")
    cats = []
    for cat, causes in categories.items():
        is_sel = cat == selected_category
        causes = causes if isinstance(causes, list) else [causes]
        chips = "".join(f"<span>{escape(str(c))}</span>" for c in causes) if causes else "<span>-</span>"
        badge = "<span class='badge'>selected</span>" if is_sel else ""
        cats.append(
            f"<div class='fish-cat{' sel' if is_sel else ''}'>"
            f"<div class='hd'>{escape(str(cat))}{badge}</div>"
            f"<div class='bd'>{chips}</div></div>"
        )
    pick = ""
    if selected_cause:
        pick = (
            f"<p class='fish-pick'>Selected root cause "
            f"<b>({escape(str(selected_category or ''))})</b>: {escape(str(selected_cause))}</p>"
        )
    return (
        "<section class='rca-card'><h2 class='rca-h2'>Fishbone Cause Categories</h2>"
        f"<div class='fish'>{''.join(cats)}</div>{pick}</section>"
    )


def _fault_tree_section(detail: dict[str, Any]) -> str:
    top = detail.get("top_event", "")
    gates = detail.get("gates", []) or []
    gate_items = []
    for gate in gates:
        gtype = str(gate.get("type", "OR")).upper()
        gcls = "g and" if gtype == "AND" else "g"
        children = "".join(
            f"<li class='leaf'>{escape(str(c))}</li>" for c in (gate.get("children", []) or [])
        )
        gate_items.append(
            f"<li><span class='gate'><span class='{gcls}'>{escape(gtype)}</span>"
            f"{escape(str(gate.get('event', '')))}</span><ul>{children}</ul></li>"
        )
    basics = detail.get("basic_causes", []) or []
    basics_html = ""
    if basics:
        items = "".join(f"<li class='leaf'>{escape(str(b))}</li>" for b in basics)
        basics_html = f"<div class='basics'><p class='lbl'>Basic causes</p><ul>{items}</ul></div>"
    return (
        "<section class='rca-card'><h2 class='rca-h2'>Fault Tree (Simplified)</h2>"
        f"<div class='ftree'><p class='top'>Top event - {escape(str(top))}</p>"
        f"<ul>{''.join(gate_items)}</ul>{basics_html}</div></section>"
    )


def _mermaid_label(text: str, limit: int = 64) -> str:
    """Make text safe for a Mermaid node label inside double quotes."""
    text = " ".join(text.split())
    if len(text) > limit:
        text = text[: limit - 3].rstrip() + "..."
    return (
        text.replace("&", "&amp;")
        .replace('"', "&quot;")
        .replace("[", "&#91;")
        .replace("]", "&#93;")
        .replace("{", "&#123;")
        .replace("}", "&#125;")
        .replace("(", "&#40;")
        .replace(")", "&#41;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _mermaid_tree(report: RCAReport) -> str:
    """A vertical 5-Why tree: problem -> deepening why nodes -> root cause."""
    if not report.why_chain:
        return ""
    lines = ["graph TD"]
    prob = _mermaid_label(report.problem, 70)
    lines.append(f'  P["Problem<br/>{prob}"]:::problem')
    prev = "P"
    for entry in report.why_chain:
        node = f"W{entry.index}"
        label = _mermaid_label(entry.answer, 72)
        lines.append(f'  {prev} -->|why?| {node}["Why {entry.index}<br/>{label}"]')
        prev = node
    rc = _mermaid_label(report.root_cause, 80)
    lines.append(f'  {prev} --> RC["Root cause<br/>{rc}"]:::root')
    lines.append("  classDef problem fill:#fff7ed,stroke:#ea580c,stroke-width:1.5px,color:#111827;")
    lines.append("  classDef default fill:#ffffff,stroke:#0f766e,stroke-width:1.5px,color:#111827;")
    lines.append("  classDef root fill:#0f172a,stroke:#0f172a,color:#ffffff;")
    graph = "\n".join(lines)
    return (
        "<section class='rca-card tree-card'><h2 class='rca-h2'>5-Why Tree</h2>"
        "<p class='hint'>Each step deepens the cause; the final node is the durable root cause.</p>"
        f"<div class='mermaid-wrap'><pre class='mermaid'>{escape(graph)}</pre>"
        "<div class='tree-fallback'>Interactive tree unavailable offline - see the "
        "Why Chain above for the same path.</div></div></section>"
    )


# --------------------------------------------------------------------------- #
# Public API
# --------------------------------------------------------------------------- #
def render_report_body(report: RCAReport, *, include_tree: bool = True) -> str:
    """Render the semantic report body (no document shell, no <style>)."""
    detail = report.method_detail or {}
    method_sections = ""
    if isinstance(detail.get("fishbone"), dict):
        method_sections += _fishbone_section(detail["fishbone"])
    if isinstance(detail.get("fault_tree"), dict):
        method_sections += _fault_tree_section(detail["fault_tree"])

    tree = _mermaid_tree(report) if (include_tree and not method_sections) else ""

    return (
        "<article class='rca-report rca-root'>"
        "<header class='rca-hero'>"
        "<p class='rca-eyebrow'>RCA Assistant Report</p>"
        "<h1 class='rca-title'>Root Cause Analysis</h1>"
        f"<p class='rca-hero-problem'>{escape(report.problem)}</p>"
        f"<div class='rca-meta'>{_meta_tags(report)}{_confidence_chip(report)}</div>"
        "</header>"
        "<div class='rca-body'>"
        f"<section class='rca-card'><h2 class='rca-h2'>Executive Summary</h2>"
        f"<p class='rca-prose rca-lead'>{escape(report.summary)}</p></section>"
        f"{_memory_section(report)}"
        f"{_why_chain_section(report)}"
        f"{tree}"
        f"{method_sections}"
        "<section class='rca-card'><h2 class='rca-h2'>Root Cause</h2>"
        "<div class='rca-root-cause'><p class='lbl'>Identified root cause</p>"
        f"<p>{escape(report.root_cause)}</p></div></section>"
        f"{_list_card('Contributing Factors', report.contributing_factors, 'dot')}"
        f"{_list_card('Recommendations', report.recommendations, 'num')}"
        f"{_list_card('Assumptions', report.assumptions, 'dot')}"
        f"{_list_card('Evidence Needed', report.evidence_needed, 'check')}"
        f"{_notes_card('Validation Notes', report.validation_notes)}"
        "<section class='rca-card'><div class='rca-disclaimer'>"
        "<span class='i'>i</span><span>" + escape(DISCLAIMER) + "</span></div></section>"
        "</div></article>"
    )


def build_html(report: RCAReport, *, include_tree: bool = True) -> str:
    """Render a full, standalone, styled HTML document for the report."""
    body = render_report_body(report, include_tree=include_tree)
    has_tree = "class='mermaid'" in body
    mermaid_script = ""
    if has_tree:
        mermaid_script = (
            f"<script src='{MERMAID_CDN}'></script>"
            "<script>"
            "(function(){function fail(){document.querySelectorAll('.tree-card')"
            ".forEach(function(c){c.classList.add('failed')});}"
            "function fixContrast(){"
            "document.querySelectorAll('.mermaid svg .node:not(.root) foreignObject *,"
            ".mermaid svg .node:not(.root) .nodeLabel,.mermaid svg .node:not(.root) .label,"
            ".mermaid svg .edgeLabel,.mermaid svg .edgeLabel *').forEach(function(el){"
            "el.style.color='#111827';el.style.fill='#111827';});"
            "document.querySelectorAll('.mermaid svg .node.root foreignObject *,"
            ".mermaid svg .node.root .nodeLabel,.mermaid svg .node.root .label').forEach(function(el){"
            "el.style.color='#ffffff';el.style.fill='#ffffff';});}"
            "try{if(window.mermaid){mermaid.initialize({startOnLoad:false,"
            "theme:'base',themeVariables:{primaryColor:'#ffffff',primaryBorderColor:'#0f766e',"
            "primaryTextColor:'#111827',secondaryColor:'#fff7ed',tertiaryColor:'#ecfdf5',"
            "nodeTextColor:'#111827',edgeLabelBackground:'#ffffff',lineColor:'#64748b',"
            "textColor:'#111827',titleColor:'#111827',fontFamily:'Inter,system-ui,sans-serif'}});"
            "mermaid.run().then(fixContrast).catch(fail);}else{fail();}}catch(e){fail();}"
            "setTimeout(function(){if(!document.querySelector('.mermaid svg, .mermaid[data-processed]'))fail();},2500);"
            "})();"
            "</script>"
        )
    return (
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        "<title>RCA Assistant Report</title>"
        "<link rel='preconnect' href='https://fonts.googleapis.com'>"
        "<link href='https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap' rel='stylesheet'>"
        f"<style>{REPORT_CSS}\nbody{{margin:0;background:var(--bg);padding:32px 18px}}</style>"
        "</head><body>"
        f"{body}{mermaid_script}"
        "</body></html>"
    )


def report_summary_json(report: RCAReport) -> str:
    """Compact JSON of the chrome-relevant fields, for the web UI header."""
    return json.dumps(
        {
            "problem": report.problem,
            "confidence": report.confidence,
            "method": report.method,
            "method_label": METHOD_LABELS.get(report.method or "", report.method),
            "source_model": report.source_model,
            "latency_seconds": report.latency_seconds,
            "root_cause": report.root_cause,
            "known_issue_matches": len(report.known_issue_matches),
        }
    )
