"""PDF report generator for Agentic RCA reports.

Renders a validated RCAReport into a professional multi-section PDF using
ReportLab Platypus. The layout is deliberately simple: a title block, metadata
line, section dividers, a 5-Why table, and a footer with page numbers and an
AI-disclosure disclaimer on every page.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from schemas import RCAReport


ACCENT = colors.HexColor("#1f3a5f")
LIGHT_ROW = colors.HexColor("#eef2f7")
RULE_GREY = colors.HexColor("#c8cfd8")
FOOTER_GREY = colors.HexColor("#6b7280")

DISCLAIMER = (
    "This root cause analysis was generated by an AI system from a plain-English "
    "problem statement. It is a reasoning aid, not a verdict: validate the causal "
    "chain against logs, metrics, and timelines before acting on it."
)


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "RCATitle",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=20,
            textColor=ACCENT,
            spaceAfter=2,
            alignment=TA_LEFT,
        ),
        "meta": ParagraphStyle(
            "RCAMeta",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            textColor=FOOTER_GREY,
            spaceAfter=10,
        ),
        "heading": ParagraphStyle(
            "RCAHeading",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=12.5,
            textColor=ACCENT,
            spaceBefore=14,
            spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "RCABody",
            parent=base["BodyText"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            spaceAfter=6,
        ),
        "cell": ParagraphStyle(
            "RCACell",
            parent=base["BodyText"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
        ),
        "cell_header": ParagraphStyle(
            "RCACellHeader",
            parent=base["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=12,
            textColor=colors.white,
        ),
        "root_cause": ParagraphStyle(
            "RCARootCause",
            parent=base["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=10.5,
            leading=15,
            textColor=ACCENT,
        ),
        "bullet": ParagraphStyle(
            "RCABullet",
            parent=base["BodyText"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            leftIndent=10,
            spaceAfter=3,
        ),
    }


def _heading(text: str, styles: dict[str, ParagraphStyle]) -> list:
    """A section heading with a divider rule underneath."""
    return [
        Paragraph(text, styles["heading"]),
        HRFlowable(width="100%", thickness=0.7, color=RULE_GREY, spaceAfter=6),
    ]


def _why_table(report: RCAReport, styles: dict[str, ParagraphStyle]) -> Table:
    rows: list[list] = [
        [
            Paragraph("#", styles["cell_header"]),
            Paragraph("Why question", styles["cell_header"]),
            Paragraph("Answer", styles["cell_header"]),
        ]
    ]
    for entry in report.why_chain:
        rows.append(
            [
                Paragraph(str(entry.index), styles["cell"]),
                Paragraph(entry.question, styles["cell"]),
                Paragraph(entry.answer, styles["cell"]),
            ]
        )
    table = Table(rows, colWidths=[10 * mm, 62 * mm, 88 * mm], repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_ROW]),
                ("GRID", (0, 0), (-1, -1), 0.4, RULE_GREY),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return table


def _footer(canvas, doc) -> None:
    canvas.saveState()
    width, _ = A4
    canvas.setStrokeColor(RULE_GREY)
    canvas.setLineWidth(0.5)
    canvas.line(18 * mm, 16 * mm, width - 18 * mm, 16 * mm)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(FOOTER_GREY)
    canvas.drawString(
        18 * mm, 12 * mm, "Agentic RCA MCP Server — AI-generated draft, verify before acting"
    )
    canvas.drawRightString(width - 18 * mm, 12 * mm, f"Page {doc.page}")
    canvas.restoreState()


def build_pdf(report: RCAReport, output_path: str | Path) -> Path:
    """Render an RCAReport to a polished PDF and return the output path."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    styles = _styles()
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=22 * mm,
        title="Agentic RCA Report",
        author="Agentic RCA MCP Server",
    )

    generated_at = datetime.now().strftime("%d %b %Y %H:%M")
    meta_bits = [f"Generated {generated_at}"]
    if report.source_model:
        meta_bits.append(f"model: {report.source_model}")
    if report.prompt_version:
        meta_bits.append(f"prompt: {report.prompt_version}")
    if report.latency_seconds is not None:
        meta_bits.append(f"latency: {report.latency_seconds}s")

    story: list = [
        Paragraph("Agentic Root Cause Analysis", styles["title"]),
        Paragraph(" &nbsp;·&nbsp; ".join(meta_bits), styles["meta"]),
        HRFlowable(width="100%", thickness=1.2, color=ACCENT, spaceAfter=10),
    ]

    story += _heading("Problem", styles)
    story.append(Paragraph(report.problem, styles["body"]))

    story += _heading("Executive Summary", styles)
    story.append(Paragraph(report.summary, styles["body"]))

    story += _heading("Why Chain", styles)
    story.append(_why_table(report, styles))
    story.append(Spacer(1, 4))

    story += _heading("Root Cause", styles)
    root_box = Table(
        [[Paragraph(report.root_cause, styles["root_cause"])]],
        colWidths=[160 * mm],
    )
    root_box.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), LIGHT_ROW),
                ("BOX", (0, 0), (-1, -1), 0.8, ACCENT),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(root_box)

    story += _heading("Contributing Factors", styles)
    for factor in report.contributing_factors:
        story.append(Paragraph(f"• {factor}", styles["bullet"]))

    story += _heading("Recommendations", styles)
    for index, rec in enumerate(report.recommendations, start=1):
        story.append(Paragraph(f"{index}. {rec}", styles["bullet"]))

    story.append(Spacer(1, 10))
    story += _heading("Disclaimer", styles)
    story.append(Paragraph(DISCLAIMER, styles["meta"]))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return output_path
