"""PDF report generator for Agentic RCA reports.

Renders a validated RCAReport into a professional multi-section PDF using
ReportLab Platypus: title block, metadata line, confidence chip, section
dividers, the canonical why-chain table, a method-aware section (Fishbone
categories or Fault-Tree outline), the Phase 4 quality fields (assumptions,
evidence needed, validation notes), and a footer with page numbers and an
AI-disclosure disclaimer on every page.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape as xml_escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from schemas import RCAReport

ATT_BLACK = colors.HexColor("#000000")
ATT_NAVY = colors.HexColor("#061a2f")
ATT_DARK_BLUE = colors.HexColor("#003b5c")
ATT_BLUE = colors.HexColor("#009fdb")
ATT_BLUE_DARK = colors.HexColor("#0073a8")
ATT_BLUE_700 = colors.HexColor("#005a8f")
ATT_BLUE_50 = colors.HexColor("#eaf8fe")
ATT_BLUE_100 = colors.HexColor("#d3f0fc")
ATT_BLUE_200 = colors.HexColor("#9fe2f6")
INK = colors.HexColor("#0b1720")
INK_SOFT = colors.HexColor("#3d5265")
INK_MUTED = colors.HexColor("#687789")
LINE_GREY = colors.HexColor("#d6dee6")

ACCENT = ATT_BLUE
LIGHT_ROW = ATT_BLUE_50
RULE_GREY = ATT_BLUE_200
FOOTER_GREY = INK_MUTED

CONFIDENCE_COLORS = {
    "high": ATT_BLUE_DARK,
    "medium": ATT_BLUE_700,
    "low": ATT_NAVY,
}

METHOD_LABELS = {
    "five_why": "Why-chain (5 Whys)",
    "fishbone": "Fishbone (Ishikawa)",
    "fault_tree": "Fault Tree (simplified)",
}

DISCLAIMER = (
    "This root cause analysis was generated by an AI system from a plain-English "
    "problem statement. It is a reasoning aid, not a verdict: validate the causal "
    "chain against logs, metrics, and timelines before acting on it."
)


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "RCATitle",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=20,
            textColor=ATT_NAVY,
            spaceAfter=2,
            alignment=TA_LEFT,
        ),
        "meta": ParagraphStyle(
            "RCAMeta",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            textColor=FOOTER_GREY,
            spaceAfter=10,
        ),
        "heading": ParagraphStyle(
            "RCAHeading",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=12.5,
            textColor=ATT_BLUE_DARK,
            spaceBefore=14,
            spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "RCABody",
            parent=base["BodyText"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=INK_SOFT,
            spaceAfter=6,
        ),
        "cell": ParagraphStyle(
            "RCACell",
            parent=base["BodyText"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=INK,
        ),
        "cell_header": ParagraphStyle(
            "RCACellHeader",
            parent=base["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=12,
            textColor=colors.white,
        ),
        "chip": ParagraphStyle(
            "RCAChip",
            parent=base["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=9.5,
            leading=12,
            textColor=colors.white,
        ),
        "root_cause": ParagraphStyle(
            "RCARootCause",
            parent=base["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=10.5,
            leading=15,
            textColor=ATT_NAVY,
        ),
        "bullet": ParagraphStyle(
            "RCABullet",
            parent=base["BodyText"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            leftIndent=10,
            textColor=INK_SOFT,
            spaceAfter=3,
        ),
        "tree": ParagraphStyle(
            "RCATree",
            parent=base["BodyText"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13,
            leftIndent=14,
            textColor=INK_SOFT,
            spaceAfter=2,
        ),
    }


def _pdf_text(value: Any) -> str:
    return xml_escape(str(value or ""))


def _pdf_label(label: str, value: Any) -> str:
    return f"<b>{_pdf_text(label)}:</b> {_pdf_text(value)}"


def _heading(text: str, styles: dict[str, ParagraphStyle]) -> list:
    """A section heading with a divider rule underneath."""
    return [
        Paragraph(text, styles["heading"]),
        HRFlowable(width="100%", thickness=0.7, color=ATT_BLUE_100, spaceAfter=6),
    ]


def _confidence_chip(report: RCAReport, styles: dict[str, ParagraphStyle]) -> Table:
    color = CONFIDENCE_COLORS.get(report.confidence, FOOTER_GREY)
    chip = Table(
        [[Paragraph(f"MODEL VERDICT: {report.confidence.upper()}", styles["chip"])]],
        colWidths=[52 * mm],
    )
    chip.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), color),
                ("ROUNDEDCORNERS", [3, 3, 3, 3]),
                ("LEFTPADDING", (0, 0), (-1, -1), 7),
                ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ]
        )
    )
    wrapper = Table([[chip]], colWidths=[52 * mm], hAlign="LEFT")
    wrapper.setStyle(TableStyle([("LEFTPADDING", (0, 0), (-1, -1), 0)]))
    return wrapper


def _why_table(report: RCAReport, styles: dict[str, ParagraphStyle]) -> Table:
    rows: list[list] = [
        [
            Paragraph("#", styles["cell_header"]),
            Paragraph("Why question", styles["cell_header"]),
            Paragraph("Answer", styles["cell_header"]),
        ]
    ]
    for entry in report.why_chain:
        rows.append(
            [
                Paragraph(_pdf_text(entry.index), styles["cell"]),
                Paragraph(_pdf_text(entry.question), styles["cell"]),
                Paragraph(_pdf_text(entry.answer), styles["cell"]),
            ]
        )
    table = Table(rows, colWidths=[10 * mm, 62 * mm, 88 * mm], repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), ATT_BLUE_700),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_ROW]),
                ("GRID", (0, 0), (-1, -1), 0.4, ATT_BLUE_100),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return table


def _fishbone_section(detail: dict[str, Any], styles: dict[str, ParagraphStyle]) -> list:
    """Render Fishbone categories as a two-column table plus the selection."""
    flow: list = list(_heading("Fishbone Cause Categories", styles))
    categories = detail.get("categories", {})
    selected_category = detail.get("selected_category")
    selected_cause = detail.get("selected_cause")

    rows: list[list] = [
        [
            Paragraph("Category", styles["cell_header"]),
            Paragraph("Candidate causes", styles["cell_header"]),
        ]
    ]
    for category, causes in categories.items():
        label = f"{category} (selected)" if category == selected_category else str(category)
        cause_text = "; ".join(str(c) for c in causes) if causes else "-"
        rows.append(
            [Paragraph(_pdf_text(label), styles["cell"]), Paragraph(_pdf_text(cause_text), styles["cell"])]
        )
    table = Table(rows, colWidths=[38 * mm, 122 * mm], repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), ATT_BLUE_700),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_ROW]),
                ("GRID", (0, 0), (-1, -1), 0.4, ATT_BLUE_100),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    flow.append(table)
    if selected_cause:
        flow.append(Spacer(1, 4))
        flow.append(
            Paragraph(
                f"Selected root cause ({_pdf_text(selected_category)}): {_pdf_text(selected_cause)}",
                styles["body"],
            )
        )
    return flow


def _fault_tree_section(detail: dict[str, Any], styles: dict[str, ParagraphStyle]) -> list:
    """Render the simplified fault tree as an indented outline."""
    flow: list = list(_heading("Fault Tree (Simplified)", styles))
    top_event = detail.get("top_event", "")
    flow.append(Paragraph(_pdf_label("Top event", top_event), styles["body"]))
    for gate in detail.get("gates", []) or []:
        gate_type = str(gate.get("type", "OR")).upper()
        event = gate.get("event", "")
        flow.append(Paragraph(f"[{_pdf_text(gate_type)}] {_pdf_text(event)}", styles["tree"]))
        for child in gate.get("children", []) or []:
            flow.append(
                Paragraph(f"- {_pdf_text(child)}", styles["tree"]),
            )
    basic = detail.get("basic_causes", []) or []
    if basic:
        flow.append(Spacer(1, 4))
        flow.append(Paragraph("<b>Basic causes:</b>", styles["body"]))
        for cause in basic:
            flow.append(Paragraph(f"- {_pdf_text(cause)}", styles["bullet"]))
    return flow


def _string_list_section(
    title: str,
    items: list[str],
    styles: dict[str, ParagraphStyle],
    numbered: bool = False,
) -> list:
    if not items:
        return []
    flow: list = list(_heading(title, styles))
    for index, item in enumerate(items, start=1):
        prefix = f"{index}." if numbered else "-"
        flow.append(Paragraph(f"{prefix} {_pdf_text(item)}", styles["bullet"]))
    return flow


def _memory_section(report: RCAReport, styles: dict[str, ParagraphStyle]) -> list:
    matches = report.known_issue_matches
    if not matches:
        return []

    total = len(matches)
    visible = matches[:3]
    top = visible[0]
    flow: list = list(_heading("Past RCA Memory", styles))
    flow.append(
        Paragraph(
            f"Found {total} matching past RCA record{'s' if total != 1 else ''}. "
            f"Showing top {len(visible)} here; download the Excel workbook for the full list.",
            styles["body"],
        )
    )
    rows: list[list] = [
        [
            Paragraph("Incident", styles["cell_header"]),
            Paragraph("Score", styles["cell_header"]),
            Paragraph("Service", styles["cell_header"]),
            Paragraph("Date", styles["cell_header"]),
        ],
        [
            Paragraph(_pdf_text(top.incident_id), styles["cell"]),
            Paragraph(_pdf_text(f"{round(top.similarity_score * 100)}% match"), styles["cell"]),
            Paragraph(_pdf_text(top.service_name or "not recorded"), styles["cell"]),
            Paragraph(_pdf_text(top.date or "not recorded"), styles["cell"]),
        ],
    ]
    table = Table(rows, colWidths=[38 * mm, 32 * mm, 54 * mm, 36 * mm], repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), ATT_BLUE_700),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_ROW]),
                ("GRID", (0, 0), (-1, -1), 0.4, ATT_BLUE_100),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    flow.append(table)
    flow.append(Spacer(1, 5))
    flow.append(Paragraph(_pdf_label("Known root cause", top.root_cause), styles["body"]))
    if top.immediate_fix:
        flow.append(Paragraph(_pdf_label("Immediate fix", top.immediate_fix), styles["body"]))
    if top.evidence_checked:
        flow.append(Paragraph(_pdf_label("Evidence checked", top.evidence_checked), styles["body"]))
    flow.append(Paragraph(_pdf_label("Match reason", top.match_reason), styles["body"]))

    for match in visible[1:]:
        flow.append(
            Paragraph(
                f"- {_pdf_text(match.incident_id)} ({round(match.similarity_score * 100)}%): "
                f"{_pdf_text(match.root_cause)}",
                styles["bullet"],
            )
        )
    return flow


def _footer(canvas, doc) -> None:
    canvas.saveState()
    width, _ = A4
    canvas.setStrokeColor(ATT_BLUE_100)
    canvas.setLineWidth(0.5)
    canvas.line(18 * mm, 16 * mm, width - 18 * mm, 16 * mm)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(FOOTER_GREY)
    canvas.drawString(
        18 * mm, 12 * mm, "RCA Assistant - AI-generated draft, verify before acting"
    )
    canvas.drawRightString(width - 18 * mm, 12 * mm, f"Page {doc.page}")
    canvas.restoreState()


def build_pdf(report: RCAReport, output_path: str | Path) -> Path:
    """Render an RCAReport to a polished PDF and return the output path."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    styles = _styles()
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=22 * mm,
        title="RCA Assistant Report",
        author="RCA Assistant",
    )

    generated_at = datetime.now().strftime("%d %b %Y %H:%M")
    meta_bits = [f"Generated {generated_at}"]
    method_label = METHOD_LABELS.get(report.method or "five_why", report.method)
    meta_bits.append(f"method: {method_label}")
    if report.source_model:
        meta_bits.append(f"model: {report.source_model}")
    if report.prompt_version:
        meta_bits.append(f"prompt: {report.prompt_version}")
    if report.latency_seconds is not None:
        meta_bits.append(f"latency: {report.latency_seconds}s")
    if report.known_issue_matches:
        meta_bits.append(f"memory: {len(report.known_issue_matches)} matches")

    story: list = [
        Paragraph("RCA Assistant Report", styles["title"]),
        Paragraph(" &nbsp;-&nbsp; ".join(_pdf_text(bit) for bit in meta_bits), styles["meta"]),
        _confidence_chip(report, styles),
        Spacer(1, 6),
        HRFlowable(width="100%", thickness=1.2, color=ATT_BLUE, spaceAfter=10),
    ]

    story += _heading("Problem", styles)
    story.append(Paragraph(_pdf_text(report.problem), styles["body"]))

    story += _heading("Executive Summary", styles)
    story.append(Paragraph(_pdf_text(report.summary), styles["body"]))

    story += _memory_section(report, styles)

    story += _heading("Why Chain", styles)
    story.append(_why_table(report, styles))
    story.append(Spacer(1, 4))

    detail = report.method_detail
    if detail and detail.fishbone:
        story += _fishbone_section(detail.fishbone.model_dump(), styles)
    if detail and detail.fault_tree:
        story += _fault_tree_section(detail.fault_tree.model_dump(), styles)

    story += _heading("Root Cause", styles)
    root_box = Table(
        [[Paragraph(_pdf_text(report.root_cause), styles["root_cause"])]],
        colWidths=[160 * mm],
    )
    root_box.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), LIGHT_ROW),
                ("BOX", (0, 0), (-1, -1), 0.8, ATT_BLUE_200),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(root_box)

    story += _string_list_section("Contributing Factors", report.contributing_factors, styles)
    story += _string_list_section("Recommendations", report.recommendations, styles, numbered=True)
    story += _string_list_section("Assumptions", report.assumptions, styles)
    story += _string_list_section("Evidence Needed", report.evidence_needed, styles)
    story += _string_list_section("Validation Notes", report.validation_notes, styles)

    story.append(Spacer(1, 10))
    story += _heading("Disclaimer", styles)
    story.append(Paragraph(DISCLAIMER, styles["meta"]))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return output_path
