"""Reset the local workspace to a repeatable RCA demo baseline."""

from __future__ import annotations

import argparse
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

DEMO_INCIDENT = {
    "id": "sso-cert-rotation",
    "label": "SSO certificate rotation failures",
    "problem_statement": (
        "Enterprise SSO logins are failing for multiple tenants after the identity "
        "provider rotated its SAML signing certificate."
    ),
    "context": (
        "Symptoms: about 22% of SAML assertions rejected with signature validation "
        "errors; only tenants on the rotated IdP are affected; direct password login "
        "is unaffected. Evidence available: sso-gateway error logs, IdP rotation "
        "change ticket, federation metadata cache age metric, and tenant-level "
        "failure breakdown."
    ),
    "severity": "high",
    "system_area": "Identity & Access",
    "method": "five_why",
    "compare_method": "fault_tree",
}


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _resolve_inside(root: Path, value: str | Path, *, label: str) -> Path:
    raw = Path(value)
    path = raw if raw.is_absolute() else root / raw
    resolved = path.resolve()
    root_resolved = root.resolve()
    if resolved != root_resolved and root_resolved not in resolved.parents:
        raise ValueError(f"{label} must stay inside the repository: {resolved}")
    return resolved


def _clear_directory(path: Path, *, dry_run: bool) -> list[str]:
    removed: list[str] = []
    if not path.exists():
        if not dry_run:
            path.mkdir(parents=True, exist_ok=True)
        return removed
    if not path.is_dir():
        raise ValueError(f"Output path is not a directory: {path}")
    for item in path.iterdir():
        removed.append(str(item))
        if dry_run:
            continue
        if item.is_dir():
            shutil.rmtree(item)
        else:
            item.unlink()
    return removed


def _demo_env(*, demo_memory: Path, output_dir: Path, root: Path) -> str:
    memory_value = f"./{demo_memory.relative_to(root).as_posix()}"
    output_value = f"./{output_dir.relative_to(root).as_posix()}"
    lines = [
        "# Generated by tools/demo_reset.py",
        "LLM_PROVIDER=ollama",
        "OLLAMA_BASE_URL=http://localhost:11434/v1",
        "RCA_MODEL=qwen3:8b",
        "RCA_PROMPT_VERSION=v3",
        "RCA_MAX_RETRIES=2",
        "RCA_MAX_OUTPUT_TOKENS=4096",
        "RCA_REQUEST_TIMEOUT_SECONDS=120",
        "RCA_AGENT_TIMEOUT_SECONDS=420",
        "RCA_MAX_REVISE_ROUNDS=2",
        "RCA_VALIDATION_ENABLED=true",
        "VALIDATION_MODEL=llama3.2:latest",
        "RCA_MEMORY_ENABLED=true",
        f"RCA_MEMORY_PATH={memory_value}",
        "RCA_MEMORY_MAX_MATCHES=3",
        "RCA_MEMORY_MIN_SCORE=0.50",
        "RCA_MEMORY_WRITEBACK_ENABLED=true",
        f"OUTPUT_DIR={output_value}",
        "AUTH_ENABLED=false",
        "VITE_AUTH_ENABLED=false",
        "",
    ]
    return "\n".join(lines)


def _write_text(path: Path, content: str, *, dry_run: bool) -> None:
    if dry_run:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _write_env(
    *,
    env_path: Path,
    content: str,
    activate_env: bool,
    dry_run: bool,
) -> str | None:
    if activate_env and env_path.exists() and env_path.read_text(encoding="utf-8") != content:
        backup = env_path.with_name(
            f"{env_path.name}.backup.{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"
        )
        if not dry_run:
            shutil.copy2(env_path, backup)
        _write_text(env_path, content, dry_run=dry_run)
        return str(backup)
    _write_text(env_path, content, dry_run=dry_run)
    return None


def reset_demo(args: argparse.Namespace) -> dict[str, Any]:
    root = _repo_root()
    output_dir = _resolve_inside(root, args.output_dir, label="output-dir")
    if output_dir == root.resolve():
        raise ValueError("output-dir cannot be the repository root")

    source_memory = _resolve_inside(root, args.source_memory, label="source-memory")
    demo_memory = _resolve_inside(root, args.demo_memory, label="demo-memory")
    env_path = _resolve_inside(
        root,
        ".env" if args.activate_env else args.env_file,
        label="env-file",
    )

    removed_outputs = _clear_directory(output_dir, dry_run=args.dry_run)
    warnings: list[str] = []
    if source_memory.exists():
        if not args.dry_run:
            demo_memory.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source_memory, demo_memory)
    else:
        warnings.append(f"Source memory workbook not found: {source_memory}")

    sample_state = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "selected_incident_id": DEMO_INCIDENT["id"],
        "payload": DEMO_INCIDENT,
        "notes": [
            "Use this payload for a predictable manager demo.",
            "The UI also exposes this incident in the sample selector.",
        ],
    }
    sample_state_path = output_dir / "demo_seed_state.json"
    _write_text(
        sample_state_path,
        json.dumps(sample_state, indent=2),
        dry_run=args.dry_run,
    )

    backup = _write_env(
        env_path=env_path,
        content=_demo_env(demo_memory=demo_memory, output_dir=output_dir, root=root),
        activate_env=args.activate_env,
        dry_run=args.dry_run,
    )

    return {
        "dry_run": args.dry_run,
        "output_dir": str(output_dir),
        "removed_output_items": len(removed_outputs),
        "demo_memory": str(demo_memory),
        "env_file": str(env_path),
        "env_backup": backup,
        "sample_state": str(sample_state_path),
        "warnings": warnings,
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Reset local RCA demo state.")
    parser.add_argument("--output-dir", default="outputs", help="Output directory to clear.")
    parser.add_argument(
        "--source-memory",
        default="data/past_rca_memory_sample_repaired.xlsx",
        help="Tracked baseline memory workbook to copy from.",
    )
    parser.add_argument(
        "--demo-memory",
        default="data/demo_past_rca_memory.xlsx",
        help="Writable demo memory workbook to refresh.",
    )
    parser.add_argument(
        "--env-file",
        default=".env.demo",
        help="Env file to write when --activate-env is not used.",
    )
    parser.add_argument(
        "--activate-env",
        action="store_true",
        help="Write .env for immediate local use, backing up an existing .env first.",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print planned changes only.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    summary = reset_demo(args)
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
